#!/usr/bin/env python3
"""Build the shared render-blocking stylesheet (no external build tools)."""

from pathlib import Path
import argparse
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCES = (
    "fonts", "style", "layout", "pages", "article", "footer", "responsive",
    "particle", "theme-light", "shortcodes", "github", "lock", "music",
    "sticky", "style-memphis", "style-notebook", "style-comic",
    "style-comic-upgrade", "manga-editions",
)
OUTPUT = ROOT / "css/site-core.css"


def build():
    chunks = ['@charset "UTF-8";\n/* Generated by scripts/build-css.py. Edit the source stylesheets, then rebuild. */\n']
    for name in SOURCES:
        source = (ROOT / "css" / (name + ".css")).read_text(encoding="utf-8")
        # CSS only permits @charset as the first rule of the entire bundle.
        source = re.sub(r'\A\ufeff?@charset\s+["\']UTF-8["\'];\s*', '', source, count=1)
        chunks.append("\n/* ---- " + name + ".css ---- */\n" + source.rstrip() + "\n")
    return "".join(chunks)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated CSS needs rebuilding")
    args = parser.parse_args()
    expected = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            sys.exit("css/site-core.css is stale; run python3 scripts/build-css.py")
        print("css/site-core.css is up to date")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
        print("Wrote", OUTPUT.relative_to(ROOT))
